
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramiro
 */
public class FormClientes extends javax.swing.JFrame {
    
    MaskFormatter formatoData;
    Date data = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    PreparedStatement pstm;
    ResultSet rs;
    String tipoRegistro;
    String sexo = "M";
    String licenca = "TRIAL";
    String flg_reativacao = "N";
    ConexaoBD con;
    int id;
    
    DefaultTableModel tmClientes = new DefaultTableModel(null, new String[]{"Nome", "E-Mail", "Telefone", "Celular"}) {

        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    ListSelectionModel lsmClientes;
    List<ClientesBean> clientes;   
    DefaultTableModel tmLicencas = new DefaultTableModel(null, new String[]{"Data", "Tipo Licença", "Cód. Ativação", "Flag Re-Ativação"}) {

        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };  
    ListSelectionModel lsmLicencas;
    List<ClientesBean> licencas;    

    /**
     * Creates new form FormClientes
     */
    public FormClientes() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        buscaRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField4 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBuscaCliente = new javax.swing.JTextField();
        btBuscaCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLicencas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        tfSoftware = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rbTrial = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rbFull = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        try{     formatoData = new MaskFormatter("##/##/####"); }catch(Exception e){     JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara"); }
        tfDataAtivacao = new JFormattedTextField(formatoData);
        jLabel16 = new javax.swing.JLabel();
        tfCodAtivacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rbNao = new javax.swing.JRadioButton();
        rbSim = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        tfMotivoReativacao = new javax.swing.JTextField();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        tfIDLicencas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        try{     formatoData = new MaskFormatter("##/##/####"); }catch(Exception e){     JOptionPane.showMessageDialog(null, "Erro ao tentar aplicar a Máscara"); }
        tfDataCadastro = new JFormattedTextField(formatoData);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbM = new javax.swing.JRadioButton();
        rbF = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfFax = new javax.swing.JTextField();
        tfCEP = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfIDCliente = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEmpresa = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysClientes - Cadastro de Clientes -- rolipam Informática");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Cliente por Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel1.setText("Digite o Nome do Cliente:");

        btBuscaCliente.setText("Buscar");
        btBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfBuscaCliente)
                .addGap(18, 18, 18)
                .addComponent(btBuscaCliente)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbClientes.setModel(tmClientes);
        tbClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmClientes = tbClientes.getSelectionModel();
        lsmClientes.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if(!e.getValueIsAdjusting()){
                    tbClientesLinhaSelecionada(tbClientes);
                }
            }
        });
        jScrollPane2.setViewportView(tbClientes);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Histórico de Licenças", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        tbLicencas.setModel(tmLicencas);
        tbLicencas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmLicencas = tbLicencas.getSelectionModel();
        lsmLicencas.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if(!e.getValueIsAdjusting()){
                    tbLicencasLinhaSelecionada(tbLicencas);
                }
            }
        });
        jScrollPane1.setViewportView(tbLicencas);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("SOFTWARE:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("TIPO LICENÇA:");

        buttonGroup2.add(rbTrial);
        rbTrial.setText("TRIAL");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("(Somente p/ SysAF)");

        buttonGroup2.add(rbFull);
        rbFull.setText("FULL");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("DATA ATIVAÇÃO:");

        tfDataAtivacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("CÓD. ATIVAÇÃO:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("RE-ATIVAÇÃO:");

        buttonGroup3.add(rbNao);
        rbNao.setText("NÃO");

        buttonGroup3.add(rbSim);
        rbSim.setText("SIM");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("MOTIVO RE-ATIVAÇÃO:");

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btDeletar.setText("Excluir");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btClear.setText("Limpar");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        tfIDLicencas.setEditable(false);
        tfIDLicencas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfIDLicencas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfIDLicencas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tfIDLicencas.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tfCodAtivacao, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(tfSoftware)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbTrial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(rbFull)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(tfDataAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbSim)
                                .addGap(15, 15, 15)
                                .addComponent(rbNao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(tfMotivoReativacao))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfIDLicencas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel16, jLabel21});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel17});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btClear, btDeletar, btIncluir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(rbTrial)
                    .addComponent(jLabel22)
                    .addComponent(rbFull)
                    .addComponent(jLabel17)
                    .addComponent(tfDataAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfCodAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(rbSim)
                    .addComponent(rbNao)
                    .addComponent(tfMotivoReativacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btAlterar)
                    .addComponent(btDeletar)
                    .addComponent(btClear)
                    .addComponent(tfIDLicencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfIDLicencas, tfMotivoReativacao});

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CÓDIGO:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DATA CADASTRO:");

        tfDataCadastro.setEditable(false);
        tfDataCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOME:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SEXO:");

        buttonGroup1.add(rbM);
        rbM.setText("M");
        rbM.setEnabled(false);

        buttonGroup1.add(rbF);
        rbF.setText("F");
        rbF.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("E-MAIL:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("TELEFONE:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CELULAR:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("ESTADO:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("CIDADE:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("CEP:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("EMPRESA:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("FAX:");

        tfFax.setEditable(false);

        tfCEP.setEditable(false);

        tfEstado.setEditable(false);

        tfTelefone.setEditable(false);

        tfIDCliente.setEditable(false);
        tfIDCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfIDCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfIDCliente.setFocusable(false);

        tfNome.setEditable(false);

        tfEmail.setEditable(false);

        tfCelular.setEditable(false);

        tfCidade.setEditable(false);

        tfEmpresa.setEditable(false);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(tfCidade)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNome))
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbM)
                                .addGap(65, 65, 65)
                                .addComponent(rbF))
                            .addComponent(tfFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelar, btEditar, btExcluir, btLimpar, btNovo, btSalvar});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCelular, tfFax, tfTelefone});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(rbM)
                    .addComponent(rbF)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btCancelar)
                    .addComponent(btExcluir)
                    .addComponent(btEditar)
                    .addComponent(btSalvar)
                    .addComponent(btNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCancelar, btEditar, btExcluir, btLimpar, btNovo, btSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-738)/2, 816, 738);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tipoRegistro = "novo";
        limparCampos();                
        geraIDNovoCadastro();
        habilitarCampos();
        tfDataCadastro.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void geraIDNovoCadastro(){
        try {
            con = new ConexaoBD();
            con.conecta();
            String sql = "select max(id) as id from clientes";
            con.executeSQL(sql);
            if (con.rs.first()) {
                id = con.rs.getInt("id");

            } else {
                id = 0;

            }
            tfIDCliente.setText("" + (id + 1));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Gerar ID!");
        } finally {
            con.desconecta();
        }        
    }
    
    private void limparCampos(){
        limparCamposCadastro();
        limparCamposLicencas();
    }
    
    private void limparCamposCadastro(){
        tbClientes.getSelectionModel().clearSelection();
        tfIDCliente.setText("");
        tfDataCadastro.setText("");
        tfNome.setText("");
        tfEmail.setText("");
        tfTelefone.setText("");
        tfCelular.setText("");
        tfEstado.setText("");
        tfCidade.setText("");
        tfCEP.setText("");
        tfEmpresa.setText("");
        tfFax.setText("");
    }
    
    private void limparCamposLicencas(){
        tbLicencas.getSelectionModel().clearSelection();
        tfSoftware.setText("");
        tfDataAtivacao.setText("");
        tfCodAtivacao.setText("");
        tfMotivoReativacao.setText("");
        tfIDLicencas.setText("");
    }
    
    private void habilitarCampos(){
        tfDataCadastro.setEditable(true);
        tfNome.setEditable(true);
        tfEmail.setEditable(true);
        tfTelefone.setEditable(true);
        tfCelular.setEditable(true);
        tfEstado.setEditable(true);
        tfCidade.setEditable(true);
        tfCEP.setEditable(true);
        tfEmpresa.setEditable(true);
        tfFax.setEditable(true);   
        rbM.setEnabled(true);
        rbF.setEnabled(true);
    }
    
    private void desabilitarCampos(){
        tfDataCadastro.setEditable(false);
        tfNome.setEditable(false);
        tfEmail.setEditable(false);
        tfTelefone.setEditable(false);
        tfCelular.setEditable(false);
        tfEstado.setEditable(false);
        tfCidade.setEditable(false);
        tfCEP.setEditable(false);
        tfEmpresa.setEditable(false);
        tfFax.setEditable(false);    
        rbM.setEnabled(false);
        rbF.setEnabled(false);        
    }
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // Salva ou Altera um registro
        if (tipoRegistro.equals("novo")) {
            gravaRegistroCliente();
        } else {
            alteraRegistroCliente();
        }        
        limparCampos();
        desabilitarCampos();
        // Atualiza TB Clientes
        buscaRegistro();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void gravaRegistroCliente(){
        ClientesBean cb = new ClientesBean();
        ClientesControl cc = new ClientesControl();
        java.sql.Date d;
        
        cb.setId_cliente(Integer.parseInt(tfIDCliente.getText()));
        try{
            d = new java.sql.Date(sdf.parse(tfDataCadastro.getText()).getTime());
            cb.setData_cadastro(d);
        }catch(Exception e){
            e.printStackTrace();
        }
        cb.setNome(tfNome.getText());
        if(rbM.isSelected()){
            sexo = "M";
        }else if(rbF.isSelected()){
            sexo = "F";
        }
        cb.setSexo(sexo);
        cb.setEmail(tfEmail.getText());
        cb.setTelefone(tfTelefone.getText());
        cb.setCelular(tfCelular.getText());
        cb.setEstado(tfEstado.getText());
        cb.setCidade(tfCidade.getText());
        cb.setCep(tfCEP.getText());
        cb.setEmpresa(tfEmpresa.getText());
        cb.setFax(tfFax.getText());
        cc.gravarCliente(cb);
    }
    
    private void alteraRegistroCliente(){
        ClientesBean cb = new ClientesBean();
        ClientesControl cc = new ClientesControl();
        
        cb.setId_cliente(Integer.parseInt(tfIDCliente.getText()));
        cb.setNome(tfNome.getText());
        if(rbM.isSelected()){
            sexo = "M";
        }else if(rbF.isSelected()){
            sexo = "F";
        }
        cb.setSexo(sexo);
        cb.setEmail(tfEmail.getText());
        cb.setTelefone(tfTelefone.getText());
        cb.setCelular(tfCelular.getText());
        cb.setEstado(tfEstado.getText());
        cb.setCidade(tfCidade.getText());
        cb.setCep(tfCEP.getText());
        cb.setEmpresa(tfEmpresa.getText());
        cb.setFax(tfFax.getText());
        cc.alterarCliente(cb);    
    }
    
    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        tipoRegistro = "alteração";
        if(tbClientes.getSelectedRow() != -1){
            habilitarCampos();
            tfDataCadastro.setEditable(false);
            tfNome.requestFocus();
        }else {
            JOptionPane.showMessageDialog(null, "Selecione uma Linha na Tabela para Alterar.");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if(tbClientes.getSelectedRow() != -1){
            excluirCliente();
            limparCampos();
            buscaRegistro();
        }else {
            JOptionPane.showMessageDialog(null, "Selecione uma Linha na Tabela para Alterar.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void excluirCliente(){
        con = new ConexaoBD();
        con.conecta();
        try {
            String sql = "select * from clientes where id=" + tfIDCliente.getText();
            con.executeSQL(sql);
            con.rs.first();
            String nome = "Deletar Cliente " + con.rs.getString("nome") + "?";
            int opcao = JOptionPane.showConfirmDialog(null, nome, "Deletar Cliente", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {
                sql = "delete from clientes where id=" + tfIDCliente.getText();
                int excluiu = con.stm.executeUpdate(sql);
                if (excluiu == 1) {
                    JOptionPane.showMessageDialog(null, "Registro Excluído com Sucesso!");
                }
            } else {
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Tentar Excluir o Registro!");
        } finally {
            con.desconecta();
        }        
    }
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limparCampos();
        desabilitarCampos();           
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
        while(tmLicencas.getRowCount() > 0){
            tmLicencas.removeRow(0);
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaClienteActionPerformed
        buscaRegistro();
    }//GEN-LAST:event_btBuscaClienteActionPerformed

    private void buscaRegistro() {
        ClientesControl cc = new ClientesControl();
        clientes = cc.listarClientes("%" + tfBuscaCliente.getText() + "%");
        mostrarClientes(clientes);
    }

    private void mostrarClientes(List<ClientesBean> clientes) {
        tbClientes.getColumnModel().getColumn(0).setPreferredWidth(90); // Nome
        tbClientes.getColumnModel().getColumn(1).setPreferredWidth(30); // Telefone
        tbClientes.getColumnModel().getColumn(2).setPreferredWidth(30); // Celular
        tbClientes.getColumnModel().getColumn(3).setPreferredWidth(50); // Email

        while (tmClientes.getRowCount() > 0) {
            tmClientes.removeRow(0);
        }

        if (clientes.size() == 0) {
            //JOptionPane.showMessageDialog(this, "Nenhum Paciente Encontrado!");
        } else {
        }
        String[] campos = new String[]{null, null, null, null};
        for (int i = 0; i < clientes.size(); i++) {

            tmClientes.addRow(campos);
            tmClientes.setValueAt(clientes.get(i).getNome(), i, 0);
            tmClientes.setValueAt(clientes.get(i).getTelefone(), i, 1);
            tmClientes.setValueAt(clientes.get(i).getCelular(), i, 2);
            tmClientes.setValueAt(clientes.get(i).getEmail(), i, 3);
        }
    }    
    
    private void buscaLicenca() {
        ClientesControl cc = new ClientesControl();
        licencas = cc.listarLicencas(Integer.parseInt(tfIDCliente.getText()));
        mostrarLicencas(licencas);
    }    
    
    private void mostrarLicencas(List<ClientesBean> licencas) {
        tbLicencas.getColumnModel().getColumn(0).setPreferredWidth(20); // Data
        tbLicencas.getColumnModel().getColumn(1).setPreferredWidth(20); // Tipo Licença
        tbLicencas.getColumnModel().getColumn(2).setPreferredWidth(50); // Cod. Ativação
        tbLicencas.getColumnModel().getColumn(3).setPreferredWidth(10); // Flg_Reativação

        while (tmLicencas.getRowCount() > 0) {
            tmLicencas.removeRow(0);
        }

        if (clientes.size() == 0) {
            //JOptionPane.showMessageDialog(this, "Nenhum Paciente Encontrado!");
        } else {
        }
        String[] campos = new String[]{null, null, null, null};
        for (int i = 0; i < licencas.size(); i++) {

            tmLicencas.addRow(campos);
            if(licencas.get(i).getData_ativacao() == null){
                tmLicencas.setValueAt("", i, 0);
            }else{
                tmLicencas.setValueAt(sdf.format(licencas.get(i).getData_ativacao()), i, 0);
            }            
            tmLicencas.setValueAt(licencas.get(i).getTipo_licenca(), i, 1);
            tmLicencas.setValueAt(licencas.get(i).getCod_ativacao(), i, 2);
            tmLicencas.setValueAt(licencas.get(i).getReativacao(), i, 3);
        }
    }    
    
    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        geraIDNovoLicenca();
        // Salva os dados no banco de dados
        salvarLicenca();
        limparCamposLicencas();
        // Atualiza Tabela de histórico de licenças
        buscaLicenca();
    }//GEN-LAST:event_btIncluirActionPerformed

    private void geraIDNovoLicenca(){
        try {
            con = new ConexaoBD();
            con.conecta();
            String sql = "select max(id) as id from licencas";
            con.executeSQL(sql);
            if (con.rs.first()) {
                id = con.rs.getInt("id") + 1;

            } else {
                id = 1;

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Gerar ID!");
        } finally {
            con.desconecta();
        }        
    }   
    
    private void salvarLicenca(){
        ClientesBean cb = new ClientesBean();
        ClientesControl cc = new ClientesControl();
        java.sql.Date d;
        
        cb.setId_licenca(id);
        cb.setId_cliente(Integer.parseInt(tfIDCliente.getText()));
        cb.setSoftware(tfSoftware.getText());
        if(rbTrial.isSelected()){
            licenca = "TRIAL";
        }else if(rbFull.isSelected()){
            licenca = "FULL";
        }
        cb.setTipo_licenca(licenca);
        try{
            if(tfDataAtivacao.getText().equals("  /  /    ")){
                // Se for Licença Trial
                d = null;
            }else{
                // Se for Licença Full
                d = new java.sql.Date(sdf.parse(tfDataAtivacao.getText()).getTime());                
            }
            cb.setData_ativacao(d);
        }catch(Exception e){
            e.printStackTrace();
        }
        cb.setCod_ativacao(tfCodAtivacao.getText());
        if(rbSim.isSelected()){
            flg_reativacao = "S";
        }else if(rbNao.isSelected()){
            flg_reativacao = "N";
        }
        cb.setReativacao(flg_reativacao);
        cb.setMotivo_reativacao(tfMotivoReativacao.getText());
        cc.gravarLicenca(cb);
    }
    
    private void alterarLicenca(){
        ClientesBean cb = new ClientesBean();
        ClientesControl cc = new ClientesControl();
        java.sql.Date d;
        
        cb.setId_licenca(id);
        cb.setSoftware(tfSoftware.getText());
        if(rbTrial.isSelected()){
            licenca = "TRIAL";
        }else if(rbFull.isSelected()){
            licenca = "FULL";
        }
        cb.setTipo_licenca(licenca);
        try{
            if(tfDataAtivacao.getText().equals("  /  /    ")){
                // Se for Licença Trial
                d = null;
            }else{
                // Se for Licença Full
                d = new java.sql.Date(sdf.parse(tfDataAtivacao.getText()).getTime());                
            }
            cb.setData_ativacao(d);
        }catch(Exception e){
            e.printStackTrace();
        }
        cb.setCod_ativacao(tfCodAtivacao.getText());
        if(rbSim.isSelected()){
            flg_reativacao = "S";
        }else if(rbNao.isSelected()){
            flg_reativacao = "N";
        }
        cb.setReativacao(flg_reativacao);
        cb.setMotivo_reativacao(tfMotivoReativacao.getText());        
        cc.alterarLicenca(cb);
    }
    
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if(tbLicencas.getSelectedRow() != -1){
            // Altera os dados no banco de dados
            alterarLicenca();
            limparCamposLicencas();
            // Atualiza Tabela de histórico de licenças     
            buscaLicenca();
        }else {
            JOptionPane.showMessageDialog(null, "Selecione uma Linha na Tabela para Alterar.");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
       if(tbLicencas.getSelectedRow() != -1){
            // Apaga o registro no banco de dados
            excluirLicenca();
            limparCamposLicencas();
            // Atualiza Tabla de histórico de licenças 
            buscaLicenca();
       }else {
            JOptionPane.showMessageDialog(null, "Selecione uma Linha na Tabela para Alterar.");
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void excluirLicenca(){
        con = new ConexaoBD();
        con.conecta();
        try {
            String sql = "select * from licencas where id=" + tfIDLicencas.getText();
            con.executeSQL(sql);
            con.rs.first();
            String nome = "Deletar a Licença Selecionada?";
            int opcao = JOptionPane.showConfirmDialog(null, nome, "Deletar Licença", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {
                sql = "delete from licencas where id=" + tfIDLicencas.getText();
                int excluiu = con.stm.executeUpdate(sql);
                if (excluiu == 1) {
                    JOptionPane.showMessageDialog(null, "Registro Excluído com Sucesso!");
                }
            } else {
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Tentar Excluir o Registro!");
        } finally {
            con.desconecta();
        }        
    }    
    
    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        limparCamposLicencas();
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormClientes().setVisible(true);
            }
        });
    }
    
    private void tbClientesLinhaSelecionada(JTable tb){
        if(tb.getSelectedRow() != -1){
            // Mostra Dados nos Campos
            tfIDCliente.setText(""+clientes.get(tb.getSelectedRow()).getId_cliente());
            tfDataCadastro.setText(sdf.format(clientes.get(tb.getSelectedRow()).getData_cadastro()));
            tfNome.setText(clientes.get(tb.getSelectedRow()).getNome());
            if(clientes.get(tb.getSelectedRow()).getSexo().equals("M")){
                rbM.setSelected(true);
            }else if(clientes.get(tb.getSelectedRow()).getSexo().equals("F")){
                rbF.setSelected(true);
            }
            tfEmail.setText(clientes.get(tb.getSelectedRow()).getEmail());
            tfTelefone.setText(clientes.get(tb.getSelectedRow()).getTelefone());
            tfCelular.setText(clientes.get(tb.getSelectedRow()).getCelular());
            tfEstado.setText(clientes.get(tb.getSelectedRow()).getEstado());
            tfCidade.setText(clientes.get(tb.getSelectedRow()).getCidade());
            tfCEP.setText(clientes.get(tb.getSelectedRow()).getCep());
            tfEmpresa.setText(clientes.get(tb.getSelectedRow()).getEmpresa());
            tfFax.setText(clientes.get(tb.getSelectedRow()).getFax());
            // Mostra Histórico de Licenças
            buscaLicenca();
        }else{
            tbClientes.getSelectionModel().clearSelection();
            limparCampos();
        }
    }
    
    private void tbLicencasLinhaSelecionada(JTable tb){
        if(tb.getSelectedRow() != -1){
            tfIDLicencas.setText(""+licencas.get(tb.getSelectedRow()).getId_licenca());
            tfSoftware.setText(licencas.get(tb.getSelectedRow()).getSoftware());
            if(licencas.get(tb.getSelectedRow()).getTipo_licenca().equals("TRIAL")){
                rbTrial.setSelected(true);
            }else if (licencas.get(tb.getSelectedRow()).getTipo_licenca().equals("FULL")){
                rbFull.setSelected(true);
            }
            tfDataAtivacao.setText(sdf.format(licencas.get(tb.getSelectedRow()).getData_ativacao()));
            tfCodAtivacao.setText(licencas.get(tb.getSelectedRow()).getCod_ativacao());
            if(licencas.get(tb.getSelectedRow()).getReativacao().equals("N")){
                rbNao.setSelected(true);
            }else if(licencas.get(tb.getSelectedRow()).getReativacao().equals("S")){
                rbSim.setSelected(true);
            }
            tfMotivoReativacao.setText(licencas.get(tb.getSelectedRow()).getMotivo_reativacao());
        }else{
            tbLicencas.getSelectionModel().clearSelection();
            limparCamposLicencas();
        }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscaCliente;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbFull;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JRadioButton rbTrial;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbLicencas;
    private javax.swing.JTextField tfBuscaCliente;
    private javax.swing.JTextField tfCEP;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCodAtivacao;
    private javax.swing.JTextField tfDataAtivacao;
    private javax.swing.JTextField tfDataCadastro;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmpresa;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfFax;
    private javax.swing.JTextField tfIDCliente;
    private javax.swing.JTextField tfIDLicencas;
    private javax.swing.JTextField tfMotivoReativacao;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSoftware;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
